export default [
  "Anemia",
  "Fifth Disease",
  "German Measles",
  "Hand-foot-and-mouth disease",
  "Herpes Zoster",
  "Herpes Zoster (Shingles)",
  "Impetigo",
  "Jaundice",
  "Measles",
  "Muehrcke",
  "Parvovirus B19",
  "Roeola",
  "Roseola",
  "Rubella",
  "Scabies",
  "Shingles",
  "Systemic lupus erythematosus",
  "Three-Day Measles",
  "acne",
  "alcohol",
  "allergic eczema",
  "anaphylaxis",
  "and mouth disease",
  "and roseola infantum",
  "angioedema",
  "athletes foot",
  "atopic",
  "atopic dermatitis",
  "autoimmune",
  "bacterial",
  "barbae",
  "basal",
  "basal cell",
  "basal cell carcinoma",
  "beard fungal",
  "belly",
  "benign",
  "bite",
  "bites",
  "black",
  "black tongue",
  "breard infection",
  "breast",
  "bull",
  "bump",
  "burn",
  "butterfly",
  "cancer",
  "carcinoma",
  "cell",
  "cellulitis",
  "chest",
  "clubbing",
  "cold burn",
  "cold sores",
  "dermatitis",
  "disease",
  "eczema",
  "edema",
  "endocarditis",
  "erythema",
  "erythema migrans",
  "exanthem subitum",
  "eye",
  "face",
  "foot",
  "freezer",
  "frost",
  "frost bite",
  "fungal",
  "fungal infection",
  "fungus",
  "gangrene",
  "general",
  "growth",
  "haemorrage",
  "hand",
  "hand foot mouth disease",
  "herpes simplex",
  "herpes-simplex",
  "hives",
  "ice",
  "impetigo",
  "infantile eczema",
  "infection",
  "insect",
  "insect bite",
  "ischaemia",
  "kerion",
  "koilonychia",
  "leg",
  "lupus",
  "lyme",
  "melanoma",
  "migrans",
  "mole",
  "mouth",
  "nail pitting",
  "neck",
  "necrosis",
  "neurodermatitis",
  "normal",
  "oedema",
  "pharyngitis",
  "pitting",
  "plantar wart",
  "plaque",
  "prurigo Besnier",
  "psoriasis",
  "rash",
  "red cheeck",
  "red cheek",
  "red face",
  "red rash",
  "ridging",
  "ringworm",
  "rosacea",
  "scalp infection",
  "scarlatina",
  "scarlet fever",
  "sixth disease",
  "skin cancer",
  "smoker",
  "smoking",
  "sore lip",
  "splinter",
  "splinter haemorrage",
  "spots",
  "squamous",
  "squamous cell",
  "strep",
  "syphilis",
  "tick",
  "tinea",
  "tinea fungal",
  "tinea pedis",
  "tongue",
  "ulcer",
  "uticaria",
  "vasculitis",
  "viral",
  "wart",
  "wart finger",
  "wart foot",
  "wart hand",
  "weals",
  "wheals",
];
